version: 2.1  # Corrected version number for CircleCI config

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/GymApp
    docker:
      - image: circleci/ruby:3.0.3-node  # Use Ruby image with Node.js support
    steps:
      - checkout

      # Step 1: Install dependencies for Rails
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Gems
          command: bundle install

      # Step 2: Install npm dependencies
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      # Step 3: Set up the database
      - run:
          name: Create and Migrate Database
          command: |
            bin/rails db:create RAILS_ENV=test
            bin/rails db:migrate RAILS_ENV=test

      # Step 4: Run tests
      - run:
          name: Run Rails Tests
          command: bin/rails test
