version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_and_test:
          filters:
            branches:
              only:
                - main

jobs:
  setup_and_test:
    working_directory: ~/GymApp
    docker:
      - image: circleci/ruby:3.1  # Use an image with Ruby
      - image: circleci/node:16.13  # Secondary image for Node.js
    steps:
      - checkout  # Checkout the code

      # Cache dependencies
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - node-cache-{{ checksum "package-lock.json" }}

      # Install Ruby dependencies
      - run:
          name: Install Ruby dependencies
          command: |
            bundle install --path vendor/bundle

      # Install Node.js dependencies
      - run:
          name: Install Node.js dependencies
          command: npm install

      # Save cache for future builds
      - save_cache:
          paths:
            - vendor/bundle
            - ./node_modules
          key: dependency-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "package-lock.json" }}

      # Run RuboCop for Ruby linting
      - run:
          name: Lint Ruby code
          command: bundle exec rubocop

      # Run ESLint for JavaScript linting
      - run:
          name: Lint JavaScript code
          command: npx eslint .

      # Run Rails tests
      - run:
          name: Run Rails tests
          command: bundle exec rails test
