version: 2.1  # Corrected version number for CircleCI config

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/GymApp
    docker:
      - image: cimg/ruby:3.2  # Next-gen Ruby image
    steps:
      - checkout

      # Install Node.js (compatible with Node.js 18.x)
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # Install npm locally
      - run:
          name: Install Local npm
          command: |
            mkdir ~/.npm-global
            npm install --prefix ~/.npm-global npm@latest
            export PATH=~/.npm-global/bin:$PATH

      # Ensure PATH is updated for subsequent steps
      - run:
          name: Update PATH for npm
          command: echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV

      # Step 1: Install dependencies for Rails
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Gems
          command: bundle install

      # Step 2: Install npm dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Step 3: Set up the database
      - run:
          name: Create and Migrate Database
          command: |
            bin/rails db:create RAILS_ENV=test
            bin/rails db:migrate RAILS_ENV=test

      # Step 4: Run tests
      - run:
          name: Run Rails Tests
          command: bin/rails test
